apiVersion: caos.ch/v1
kind: Boom
metadata:
  name: boom
  namespace: caos-system
spec:
  boom:
    version: v4.0.0
  forceApply: true
  currentStatePath: caos-internal/boom
  apiGateway:
    deploy: true
    replicaCount: 1
    proxyProtocol: true
  metricCollection:
    deploy: false
  logCollection:
    deploy: false
  nodeMetricsExporter:
    deploy: false
  systemdMetricsExporter:
    deploy: false
  monitoring:
    deploy: false
  kubeMetricsExporter:
    deploy: false
  reconciling:
    deploy: false
  metricsPersisting:
    deploy: false
  logsPersisting:
    deploy: false
  metricsServer:
    deploy: false
  preApply:
    deploy: false
    folder: preapply
