version: 2
updates:
- package-ecosystem: npm
  directory: "/console"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: "docker"
  directory: "/build/docker/zitadel"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: "docker"
  directory: "/build/docker/operator"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: npm
  directory: "/site"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
