project_name: zitadel

release:
  github:
    owner: zitadel
    name: zitadel
  draft: true
  prerelease: auto

before:
  hooks:
    - docker build -f build/grpc/Dockerfile -t zitadel-base:local .
    - docker build -f build/zitadel/Dockerfile . -t zitadel-go-test --target go-codecov -o .artifacts/codecov
    - docker build -f build/zitadel/Dockerfile . -t zitadel-go-base --target go-copy -o .artifacts/grpc/go-client
    - sh -c "cp -r .artifacts/grpc/go-client/* ."
    - docker build -f build/console/Dockerfile . -t zitadel-npm-base --target npm-copy -o .artifacts/grpc/js-client
    - docker build -f build/console/Dockerfile . -t zitadel-npm-base --target angular-export -o .artifacts/console
    - sh -c "cp -r .artifacts/console/* internal/api/ui/console/static/"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dist: .artifacts/goreleaser

dockers:
- image_templates:
  - ghcr.io/zitadel/zitadel:{{ .Tag }}-amd64
  - ghcr.io/zitadel/zitadel:{{ .ShortCommit }}-amd64
  - europe-docker.pkg.dev/zitadel-common/zitadel-repo/zitadel:{{ .Tag }}-amd64
  - europe-docker.pkg.dev/zitadel-common/zitadel-repo/zitadel:{{ .ShortCommit }}-amd64
  use: buildx
  dockerfile: build/Dockerfile
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
    - ghcr.io/zitadel/zitadel:{{ .Tag }}-arm64
    - ghcr.io/zitadel/zitadel:{{ .ShortCommit }}-arm64
  use: buildx
  dockerfile: build/Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64"

archives:
- format: binary

gomod:
  proxy: false

checksum:
  name_template: 'checksums.txt'
  
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - tap:
      owner: zitadel
      name: zitadel-tap
    folder: Formula
    goarm: "7"
    homepage:  https://zitadel.ch
    description: Open source identity solution built for the container and cloud era
    license: Apache 2.0
    test: |
      system "#{bin}/zitadel -v"
    dependencies:
    - name: go
      type: optional
    - name: git
    install: |-
      bin.install "zitadel"
      bash_completion.install "completions/zitadel.bash" => "zitadel"
      zsh_completion.install "completions/zitadel.zsh" => "zitadel"
      fish_completion.install "completions/gorezitadelleaser.fish"
      man1.install "manpages/zitadel.1.gz"

announce:
  discord:
    enabled: true
    message_template: 'ZITADEL {{ .Tag }} is ready! Check the notes: https://github.com/zitadel/zitadel/releases/tag/{{ .Tag }}'