# What language dictionaries should it use? Currently Typo CI supports:
# de
# en
# en_GB
# es
# fr
# it
# pt
# pt_BR
dictionaries:
    - en
    - en_GB
    - de

# Any files/folders we should ignore?
excluded_files:
    - ".codecov/*"
    - ".github/*"
    - "build/*"
    - "k8s/*"
    - "*.min.css"
    - "*.css.map"
    - "*.min.js"
    - "*.js.map"
    - "package-lock.json"
    - "package.json"
    - ".releaserc.js"
    - ".typo-ci.yml"
    - ".gitignore"
    - "go.mod"
    - "go.sum"

# Any typos we should ignore?
excluded_words:
    - typoci

# Would you like filenames to also be spellchecked?
spellcheck_filenames: false