version: '3.8'

services:

  prepare:
    image: node:18-alpine3.15
    working_dir: /e2e
    user: '$UID'
    volumes:
      - ../../:/e2e
    command: 'sh -c "npm ci --omit=dev && npm run lint && npx wait-on http://localhost:8080/debug/ready"'
    network_mode: host

  e2e:
    image: cypress/included:12.2.0
    depends_on:
      zitadel:
        condition: 'service_started'
      db:
        condition: 'service_healthy'
      prepare:
        condition: 'service_completed_successfully'
    working_dir: /e2e
    user: '$UID'
    volumes:
      - ../../:/e2e
    network_mode: host
