version: '3.8'

services:

  proxy-enabled-tls:
    image: "nginx:1.25.3-alpine"
    volumes:
      - "./nginx-enabled-tls.conf:/etc/nginx/nginx.conf:ro"
      - "./selfsigned.crt:/etc/nginx/ssl/selfsigned.crt:ro"
      - "./selfsigned.key:/etc/nginx/ssl/selfsigned.key:ro"
    ports:
      - "443:443"
    depends_on:
      zitadel-enabled-tls:
        condition: 'service_healthy'

  proxy-external-tls:
    image: "nginx:1.25.3-alpine"
    volumes:
      - "./nginx-external-tls.conf:/etc/nginx/nginx.conf:ro"
      - "./selfsigned.crt:/etc/nginx/ssl/selfsigned.crt:ro"
      - "./selfsigned.key:/etc/nginx/ssl/selfsigned.key:ro"
    ports:
      - "443:443"
    depends_on:
      zitadel-external-tls:
        condition: 'service_healthy'
