services:
  zitadel:
    image: 'zitadel:${BUILD_DATE}'
    environment:
      # TODO: localhost?
      ZITADEL_EXTERNALDOMAIN: zitadel
      ZITADEL_FIRSTINSTANCE_CUSTOMDOMAIN: zitadel

  e2e:
    image: cypress/included:10.3.0
    container_name: cypress
    environment:
      CYPRESS_BASE_URL: http://zitadel:8080 
      CYPRESS_ORGANIZATION: zitadel
    depends_on:
    -  zitadel
    working_dir: /e2e
    volumes:
    - ${PWD}/console:/e2e
