services:
  zitadel:
    image: 'zitadel:${BUILD_DATE}'
    environment:
      # TODO: ugly
      ZITADEL_EXTERNALDOMAIN: zitadel
      ZITADEL_S3DEFAULTINSTANCE_CUSTOMDOMAIN: zitadel
      
  e2e-setup: 
    build:
      dockerfile: ./build/e2e/Dockerfile
      context: ..
    container_name: e2e-setup
    env_file:
    - ./compose.env
    environment:
      ZITADEL_DATABASE_HOST: db
    networks:
    - 'zitadel'
    volumes:
    - ${PWD}/.keys/e2e.json:/.keys/e2e.json
    depends_on:
      zitadel:
#       TODO: See PR #3816
#       condition: 'service_healthy'
        condition: service_started
  e2e:
    image: cypress/included:10.3.0
    container_name: cypress
    depends_on:
      e2e-setup:
        condition: 'service_completed_successfully'
    env_file:
    - ./compose.env
    working_dir: /e2e
    entrypoint:
    - bash
    - -c
    command:
    - ./cypress.sh run
    volumes:
    - ${PWD}/.keys/e2e.json:/.keys/e2e.json
    - ${PWD}/console:/e2e
    networks:
    - 'zitadel'

