version: '3.8'

services:
  zitadel:
    extends:
      file: ./config/cockroach/docker-compose.yaml
      service: zitadel

  db:
    extends:
      file: ./config/cockroach/docker-compose.yaml
      service: db
