openapi: "3.1.0"
info:
  version: "2.0.0"
  title: "ZITADELs API"
  description: The ZITADEL api
  termsOfService: 'https://zitadel.com/docs/legal/introduction'
  contact:
    email: hi@zitadel.com
    url: 'https://zitadel.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - "url": "https://{instance}.zitadel.cloud:{port}/{basePath}"
    "description": "The production API server"
    variables:
      instance:
        default: "test-qcon0h"
        description: The generated name of your ZITADEL Cloud Instance
      port: 
        default: "443"
      basePath: 
        default: "v2"
  - "url": "https://{instance}:{port}/{basePath}"
    "description": "A self hosted test system"
    variables:
      instance:
        default: "localhost"
        description: The generated name of your ZITADEL Cloud Instance
      port: 
        default: "80"
      basePath: 
        default: "v2"
paths:
  /authorize:
    $ref: "paths/authorize.yaml"
  /login:
    $ref: "paths/authorize.yaml"
  /Users:
    $ref: "paths/users.yaml"
  /Users/{id}:
    $ref: "paths/users_{id}.yaml"
components:
  securitySchemes:
    ## TODO Ref hardcoded url
    personalAccessToken:
      type: http
      scheme: bearer
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            read_users: read users
            search_users: search users
    openId:
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
security:
  - personalAccessToken:
    - user.read
  - oauth2:
    - user.read
  - openId:
    - user.read