version: '3.8'

services:
  zitadel:
    restart: always
    networks:
      - zitadel
    image: ghcr.io/zitadel/zitadel:v1.80.0-v2.20-amd64
    command: admin start-from-init --masterkeyFromEnv
    environment:
      - ZITADEL_MASTERKEY=${ZITADEL_MASTERKEY}
      - ZITADEL_DATABASE_HOST=db
      # TODO: Use the following variables as defaults
      - ZITADEL_EXTERNALSECURE=false
      - ZITADEL_EXTERNALDOMAIN=localhost
      - ZITADEL_S3DEFAULTINSTANCE_CUSTOMDOMAIN=localhost
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/debug"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 40s
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080

  db:
    restart: always
    networks:
      - zitadel
    image: cockroachdb/cockroach:v21.2.8
    command: start-single-node --insecure --listen-addr=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    ports:
      - 9090:8080
      - 26257:26257

networks:
  zitadel:
