version: '3'
services:
  proxy:
    image: envoyproxy/envoy:latest
    environment:
      NODE_ENV: development
    ports:
      - 9090:9090
      - 9091:9091
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml