version: '3'

services:
  docusaurus:
    image: node:lts-alpine3.15
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    command: sh -c "yarn install && yarn start --host 0.0.0.0"