[[redirects]]
  from = "/guides/deploy/*"
  to = "/docs/self-hosting/deploy/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/guides/manage/self-hosted/*"
  to = "/docs/self-hosting/manage/:splat"
  status = 301
  force = true
 
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = '''
	  max-age=31536000;
	  includeSubDomains;
	  preload'''
