# This is a workaround to address the problem around the baseUrl from docusaurus
# Be aware that this prevents the usage of the path /docs/docs
[[redirects]]
  from = "/docs/*"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/docs"
  status = 302
  force = true
 
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = '''
	  max-age=31536000;
	  includeSubDomains;
	  preload'''
