apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
    name: flow-zitadel
spec:
    filters:
      - parser:
            remove_key_name_field: true
            reserve_data: true
            parse:
                type: logfmt
      - tag_normaliser:
            metadata: ${namespace}.${container}.${pod}
            metadata_name: ${namespace_name}.${container_name}.${pod_name}
    selectors:
        app: zitadel
    outputRefs:
      - output-loki