
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: output-loki
spec:
  loki:
    buffer:
      timekey: 1m
      timekey_use_utc: true
      timekey_wait: 30s
    configure_kubernetes_labels: true
    url: http://loki.caos-system:3100
