---
apiVersion: v1
kind: Service
metadata:
  name: api-admin-v1
spec:
  ports:
  - name: rest
    port: 80
    targetPort: admin-rest
  - name: grpc
    port: 8080
    targetPort: admin-grpc
  selector:
    app: zitadel
    version: v1
