name: All in one build

on:
  pull_request:

permissions:
  contents: write
  packages: write

env:
  go_version: '1.20'

jobs:

  cache:
    uses: ./.github/workflows/cache.yml
  
  build:
    uses: ./.github/workflows/build.yml
    needs: cache
    with:
      node_version: 18
      go_version: '1.20'
      buf_version: v1.15.1
      core_hash: ${{ needs.cache.outputs.core_hash }}
      core_hit: ${{ needs.cache.outputs.core_hit }}
      console_hash: ${{ needs.cache.outputs.console_hash }}
      console_hit: ${{ needs.cache.outputs.console_hit }}
  
  compile:
    uses: ./.github/workflows/compile.yml
    needs: [cache, build]
    with:
      core_hash: ${{ needs.cache.outputs.core_hash }}
      console_hash: ${{ needs.cache.outputs.console_hash }}

  lint:
    uses: ./.github/workflows/lint.yml
    needs: cache
    if: needs.cache.outputs.core_hit != 'true' || needs.cache.outputs.console_hit != 'true'
    with:
      node_version: 18
      go_version: '1.20'
      buf_version: v1.15.1
      golangci_lint_version: v1.52.2
      core_hit: ${{ needs.cache.outputs.core_hit }}
      console_hit: ${{ needs.cache.outputs.console_hit }}

  test:
    uses: ./.github/workflows/test.yml
    needs: [cache, build]
    with:
      node_version: 18
      go_version: '1.20'
      buf_version: v1.15.1
      core_hash: ${{ needs.cache.outputs.core_hash }}

  container:
    uses: ./.github/workflows/container.yml
    needs: [lint, test, build]
    with:
      tag_name: ghcr.io/zitadel/test:${{ github.sha }}

  e2e:
    uses: ./.github/workflows/e2e.yml
    needs: [container]
    with:
      tag_name: ghcr.io/zitadel/test:${{ github.sha }}


  #release