name: All in one build

on:
  push:
    
jobs:

  api:
    uses: ./.github/workflows/api.yml
    with:
      buf: v1.15.1

  console:
    uses: ./.github/workflows/console.yml
    with:
      node: 18

  core:
    uses: ./.github/workflows/core.yml
    with:
      go: 1.19

  docs:
    uses: ./.github/workflows/docs.yml
    with:
      node: 18

  # login:
  # placeholder 

  release:
    name: release zitadel
    runs-on: ubuntu-latest
    needs: [api, core, console, docs]
    steps:
    - run: echo "This is a placeholder"