name: All in one build

on:
  pull_request:

permissions:
  contents: write
  packages: write
    
jobs:

  lint:
    uses: ./.github/workflows/lint.yml
    with:
      node_version: 18
      go_version: '1.20'
      buf_version: v1.15.1
      golangci_lint_version: v1.52.2

  unit-test:
    uses: ./.github/workflows/unit-test.yml
    with:
      node_version: 18
      go_version: '1.20'
      buf_version: v1.15.1

  build:
    uses: ./.github/workflows/build.yml
    with:
      node_version: 18
      go_version: '1.20'
      buf_version: v1.15.1

  container:
    uses: ./.github/workflows/container.yml
    needs: [lint, unit-test, build]
    with:
      tag_name: ghcr.io/zitadel/test:${{ github.sha }}

  integration-test:
    uses: ./.github/workflows/integration.yml
    needs: [build]
    with:
      go_version: '1.20'

  e2e:
    uses: ./.github/workflows/e2e.yml
    needs: [container]
    with:
      tag_name: ghcr.io/zitadel/test:${{ github.sha }}


  #release