name: All in one build

on:
  pull_request:

permissions:
  contents: write
  packages: write
    
jobs:

  # lint:
  #   uses: ./.github/workflows/lint.yml
  #   with:
  #     node_version: 18
  #     go_version: 1.19
  #     buf_version: v1.15.1

  # test:
  #   uses: ./.github/workflows/test.yml
  #   with:
  #     node_version: 18
  #     go_version: 1.19
  #     buf_version: v1.15.1

  # build:
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     node_version: 18
  #     go_version: 1.19
  #     buf_version: v1.15.1

  container:
    #uses: ./.github/workflows/container.yml
    #needs: [lint, test, build]
    name: core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: build/test.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: zitadel/test:test

  #release

  #e2e