name: All in one build

on:
  push:
    
jobs:

  api:
    uses: ./.github/workflows/api.yml
    with:
      go: 1.19

  console:
    uses: ./.github/workflows/console.yml
    with:
      node: 18

  docs:
    uses: ./.github/workflows/docs.yml
    with:
      node: 18

  release:
    name: release zitadel
    runs-on: ubuntu-latest
    needs: [api, console, docs]
    steps:
    - run: echo "This is a placeholder"