name: All in one build

on:
  pull_request:

permissions:
  contents: write
  packages: write

env:
  go_version: '1.20'

jobs:
  
  build:
    uses: ./.github/workflows/build.yml
    with:
      node_version: 18
      go_version: '1.20'
      buf_version: v1.15.1
  
  compile:
    uses: ./.github/workflows/compile.yml
    needs: build
    with:
      core_hash: ${{needs.build.outputs.core_hash}}

  lint:
    uses: ./.github/workflows/lint.yml
    with:
      node_version: 18
      go_version: '1.20'
      buf_version: v1.15.1
      golangci_lint_version: v1.52.2

  test:
    uses: ./.github/workflows/test.yml
    needs: [build]
    with:
      node_version: 18
      go_version: '1.20'
      buf_version: v1.15.1
      core_hash: core-${{ needs.build.outputs.hash }}

  container:
    uses: ./.github/workflows/container.yml
    needs: [lint, test, build]
    with:
      tag_name: ghcr.io/zitadel/test:${{ github.sha }}

  e2e:
    uses: ./.github/workflows/e2e.yml
    needs: [container]
    with:
      tag_name: ghcr.io/zitadel/test:${{ github.sha }}


  #release