name: All in one build

on:
  push:
    
jobs:

  console:
    uses: ./.github/workflows/console.yml
    with:
      node: 18

  docs:
    uses: ./.github/workflows/docs.yml
    with:
      node: 18

