name: All in one build

on:
  pull_request:

permissions:
  contents: write
  packages: write

env:
  go_version: '1.20'
  node_version: '16'

jobs:

  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
      # install node for sass
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go_version }}
      - run: make core_build
    
  console:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          cache: 'yarn'
          cache-dependency-path: console/yarn.json
      - run: make console_build


  # core:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v3
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #       with:
  #         driver-opts: ${{env.buildx_driver_opts}}
  #     - 
  #       name: Login to Docker registry
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     -
  #       name: Build
  #       uses: docker/build-push-action@v4
  #       with:
  #         context: .
  #         file: ./build/workflow.Dockerfile
  #         target: core-gathered
  #         push: false
  #         cache-to: type=registry,ref=ghcr.io/zitadel/build-cache:core,mode=max
  #         cache-from: ${{env.cache_from_params}}
  #         github-token: ${{ github.token }}
  
  # console:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v3
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #       with:
  #         driver-opts: ${{env.buildx_driver_opts}}
  #     - 
  #       name: Login to Docker registry
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     -
  #       name: Build
  #       uses: docker/build-push-action@v4
  #       with:
  #         context: .
  #         file: ./build/workflow.Dockerfile
  #         target: console
  #         push: false
  #         cache-to:  type=registry,ref=ghcr.io/zitadel/build-cache:console,mode=max
  #         cache-from: ${{env.cache_from_params}}
  #         github-token: ${{ github.token }}
  #         tags: ${{env.tag_name}}
  
  # compile:
  #   runs-on: ubuntu-latest
  #   needs: [console, core]
  #   strategy:
  #     matrix:
  #       goos: ['linux', 'darwin', 'windows']
  #       goarch: ['amd64', 'arm64']
  #   steps:
  #   -
  #     name: Checkout
  #     uses: actions/checkout@v3
  #   -
  #     name: Set up QEMU
  #     uses: docker/setup-qemu-action@v2
  #   -
  #     name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v2
  #     with:
  #       driver-opts: ${{env.buildx_driver_opts}}
  #   - 
  #     name: Login to Docker registry
  #     uses: docker/login-action@v2
  #     with:
  #       registry: ghcr.io
  #       username: ${{ github.actor }}
  #       password: ${{ secrets.GITHUB_TOKEN }}
  #   -
  #     name: Compile
  #     uses: docker/build-push-action@v4
  #     with:
  #       build-args: |
  #         "GOOS=${{matrix.goos}}"
  #         "GOARCH=${{matrix.goarch}}"
  #       context: .
  #       file: ./build/workflow.Dockerfile
  #       target: copy-executable
  #       push: false
  #       cache-to: ${{env.cache_to_params}}
  #       cache-from: ${{env.cache_from_params}}
  #       github-token: ${{ github.token }}
  #       tags: ${{env.tag_name}}
  #       outputs: type=local,dest=/tmp/zitadel
  #   -
  #     name: Upload executable
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: zitadel-${{ matrix.goos }}-${{ matrix.goarch }}
  #       path: /tmp/zitadel/.artifacts/zitadel

  # core-unit-test:
  #   runs-on: ubuntu-latest
  #   needs: [core]
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v3
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #       with:
  #         driver-opts: ${{env.buildx_driver_opts}}
  #     - 
  #       name: Login to Docker registry
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     -
  #       name: Unit tests
  #       uses: docker/build-push-action@v4
  #       with:
  #         context: .
  #         file: ./build/workflow.Dockerfile
  #         target: coverage-core-unit
  #         push: false
  #         cache-to:  ${{env.cache_to_params}}
  #         cache-from: ${{env.cache_from_params}}
  #         github-token: ${{ github.token }}
  #         tags: ${{env.tag_name}}
  #         outputs: type=local,dest=/tmp/zitadel
  #     - name: Publish coverage
  #       uses: codecov/codecov-action@v3.1.4
  #       with:
  #         file: /tmp/zitadel/coverage/profile.cov
  #         name: core-unit-tests
  #         flags: core-unit-tests

  # core-integration-test:
  #   runs-on: ubuntu-latest
  #   needs: [core]
  #   strategy:
  #     matrix:
  #       database: [cockroach, postgres]
  #   env:
  #     DB_FLAVOR: ${{ matrix.database }}
  #     ZITADEL_MASTERKEY: MasterkeyNeedsToHave32Characters
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: '0'
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #       with:
  #         driver-opts: ${{env.buildx_driver_opts}}
  #     - 
  #       name: Login to Docker registry
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     -
  #       name: Integration tests
  #       uses: docker/build-push-action@v4
  #       with:
  #         context: .
  #         file: ./build/workflow.Dockerfile
  #         target: coverage-core-integration
  #         push: false
  #         cache-to:  ${{env.cache_to_params}}
  #         cache-from: ${{env.cache_from_params}}
  #         github-token: ${{ github.token }}
  #         tags: ${{env.tag_name}}
  #         outputs: type=local,dest=/tmp/zitadel
  #     - name: Publish coverage
  #       uses: codecov/codecov-action@v3.1.4
  #       with:
  #         file: /tmp/zitadel/coverage/profile.cov
  #         name: core-integration-tests-${{ matrix.database }}
  #         flags: core-integration-tests-${{ matrix.database }}

  # lint:
  #   uses: ./.github/workflows/lint.yml
  #   with:
  #     buildx_driver_opts: |
  #       image=moby/buildkit:v0.11.6
  #     cache_from_params: |
  #       type=registry,ref=ghcr.io/zitadel/build-cache
  #       type=registry,ref=ghcr.io/zitadel/build-cache:console
  #       type=registry,ref=ghcr.io/zitadel/build-cache:core
  #       type=registry,ref=ghcr.io/zitadel/build-cache:latest
  #     cache_to_params: type=registry,ref=ghcr.io/zitadel/build-cache,mode=max,ignore-error=true
  #     tag_name: ghcr.io/zitadel/test:${{ github.sha }}

  # e2e:
  #   uses: ./.github/workflows/e2e.yml
  #   needs: [container]
  #   with:
  #     tag_name: ghcr.io/zitadel/test:${{ github.sha }}


  #release