name: api

on:
  workflow_call:
    inputs:
      buf:
        required: true
        type: string

jobs:
  
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: bufbuild/buf-setup-action@v1
      with:
        version: ${{ inputs.buf }}
    - uses: bufbuild/buf-lint-action@v1

  breaking:
    name: breaking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: bufbuild/buf-setup-action@v1
      with:
        version: ${{ inputs.buf }}
    - uses: bufbuild/buf-breaking-action@v1
      with:
        against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main"