name: api

on:
  workflow_call:
    inputs:
      buf_version:
        required: true
        type: string
    secrets:
      buf_token:
        required: true

jobs:
  
  lint:
    name: lint
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - uses: bufbuild/buf-setup-action@v1
      with:
        version: ${{ inputs.buf_version }}
    - uses: bufbuild/buf-lint-action@v1
    ## TODO add comment action with report

  breaking:
    name: breaking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: bufbuild/buf-setup-action@v1
      with:
        version: ${{ inputs.buf_version }}
    - uses: bufbuild/buf-breaking-action@v1
      with:
        against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main"

  push:
    name: push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: bufbuild/buf-setup-action@v1
      with:
        version: ${{ inputs.buf }}
    - uses: bufbuild/buf-push-action@v1
      with:
        buf_token: ${{ secrets.buf_token }}