name: Build

on:
  workflow_call:
    outputs:
      core_hash:
          description: The cache hash of the core
          value: ${{jobs.generate-core.outputs.hash}}
      console_hash:
        description: The cache hash of the console
        value: ${{jobs.console.outputs.hash}}
    inputs:
      node_version:
        required: true
        type: string
      go_version:
        required: true
        type: string
      buf_version:
        required: true
        type: string

jobs:

  #api:

  console:
    name: console
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.generate-hash.outputs.CONSOLE_HASH }}
    steps:
    - uses: actions/checkout@v3
    - id: generate-hash
      run: echo "CONSOLE_HASH=console-dist-${{ hashFiles('console/src/**', '!console/src/app/proto/**', 'console/yarn.lock') }}" >> "$GITHUB_OUTPUT"
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'
        cache-dependency-path: console/yarn.lock
    - run: (cd console ; yarn install --frozen-lockfile)
    - run: (cd console ; yarn generate)
    - run: (cd console ; yarn build)
    - uses: actions/cache/save@v3
      if: always()
      with:
        path: console/dist/console/
        key: ${{ steps.generate-hash.outputs.CONSOLE_HASH }}

  generate-core:
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.generate-hash.outputs.CORE_HASH }}
    steps:
      - uses: actions/checkout@v3
      - id: generate-hash
        run: echo "CORE_HASH=${{hashFiles('build/**', 'cmd/**', 'internal/**', 'pkg/**', 'proto/**', '!*.pb.*')}}" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go_version }}
          cache: true
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: ${{ inputs.buf_version }}
          github_token: ${{ github.token }}
      - run: make generate
      - uses: actions/cache/save@v3
        with:
          path: .
          key: core-${{ steps.generate-hash.outputs.CORE_HASH }}
