name: Build

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      go_version:
        required: true
        type: string
      buf_version:
        required: true
        type: string
      core_hash:
        required: true
        type: string
      core_hit:
        type: string
      console_hash:
        required: true
        type: string
      console_hit:
        type: string

jobs:

  #api:

  console:
    name: console
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      if: inputs.console_hit != 'true'
    - uses: actions/setup-node@v3
      if: inputs.console_hit != 'true'
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'
        cache-dependency-path: console/yarn.lock
    - run: (cd console ; yarn install --frozen-lockfile)
    - run: (cd console ; yarn generate)
    - run: (cd console ; yarn build)
    - uses: actions/cache/save@v3
      if: inputs.console_hit != 'true'
      with:
        path: console/dist/console/
        key: ${{ inputs.console_hash }}

  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: inputs.console_hit != 'true'
      - uses: actions/setup-go@v3
        if: inputs.console_hit != 'true'
        with:
          go-version: ${{ inputs.go_version }}
          cache: true
      - uses: bufbuild/buf-setup-action@v1
        if: inputs.console_hit != 'true'
        with:
          version: ${{ inputs.buf_version }}
          github_token: ${{ github.token }}
      - run: make generate
        if: inputs.console_hit != 'true'
      - uses: actions/cache/save@v3
        if: inputs.console_hit != 'true'
        with:
          path: .
          key: ${{ inputs.core_hash }}
