name: Build

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      go_version:
        required: true
        type: string
      buf_version:
        required: true
        type: string

jobs:

  #api:

  console:
    name: console
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'
        cache-dependency-path: console/yarn.lock
    - run: (cd console ; yarn install --frozen-lockfile)
    - run: (cd console ; yarn generate)
    - run: (cd console ; yarn build)
    - uses: actions/cache/save@v3
      if: always()
      with:
        path: console/dist/console/
        key: console-dist-${{ hashFiles('console/src/**', '!console/src/app/proto/**', 'console/yarn.lock') }}

  core:
    name: core
    runs-on: ubuntu-latest
    needs: console
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/cache/restore@v3
      name: restore core
      with:
        path: .
        key: core-${{ hashFiles('build/**', 'cmd/**', 'internal/**', 'pkg/**', 'proto/**') }}
    - uses: actions/cache/restore@v3
      with:
        path: console/dist/console/
        key: console-dist-${{ hashFiles('console/src/**', '!console/src/app/proto/**', 'console/yarn.lock') }}
    - name: move console to correct folder
      run: mv console/dist/console/ internal/api/ui/console/static/
    - name: build executable
      run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o zitadel-core-${{ matrix.goos }}-${{ matrix.goarch }} -ldflags="-s -w"
    - uses: actions/upload-artifact@v3
      with:
        name: zitadel-core-${{ matrix.goos }}-${{ matrix.goarch }}
        path: zitadel-core-${{ matrix.goos }}-${{ matrix.goarch }}
