name: Build

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      go_version:
        required: true
        type: string
      buf_version:
        required: true
        type: string

jobs:

  #api:

  console:
    name: console
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'
        cache-dependency-path: console/yarn.lock
    - run: (cd console ; yarn install --frozen-lockfile)
    - run: (cd console ; yarn generate)
    - run: (cd console ; yarn build)
    - run: mv console/dist/console/ internal/api/ui/console/static/
    - uses: actions/cache/save@v3
      if: always()
      with:
        path: internal/api/ui/console/static/
        key: console-dist-${{ hashFiles('console/**') }}

  core:
    name: core
    runs-on: ubuntu-latest
    needs: console
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go_version }}
    - uses: bufbuild/buf-setup-action@v1
      with:
        version: ${{ inputs.buf_version }}
        github_token: ${{ github.token }}
    - run: make generate
    - uses: actions/cache/restore@v3
      with:
        path: internal/api/ui/console/static/
        key: console-dist-${{ hashFiles('console/**') }}
    - run: ls -la internal/api/ui/console/static/
    - run: go build -o zitadel-core-${{ matrix.goos }}-${{ matrix.goarch }} -ldflags="-s -w"
    - uses: actions/upload-artifact@v3
      with:
        name: zitadel-core-${{ matrix.goos }}-${{ matrix.goarch }}
        path: zitadel-core-${{ matrix.goos }}-${{ matrix.goarch }}
