name: Cache

on: 
  workflow_call:
    outputs:
      core_hash:
        description: The cache hash of the core
        value: ${{jobs.hash.outputs.core_hash}}
      core_hit:
        description: check if already cached
        value: ${{jobs.hash.outputs.core_hit}}
      console_hash:
        description: The cache hash of the console
        value: ${{jobs.hash.outputs.console_hash}}
      console_hit:
        description: check if already cached
        value: ${{jobs.hash.outputs.console_hit}}

jobs:
  hash:
    runs-on: ubuntu-latest
    outputs:
      console_hash: ${{ steps.generate-hash.outputs.CONSOLE_HASH }}
      core_hash: ${{ steps.generate-hash.outputs.CORE_HASH }}
      api_hash: ${{ steps.generate-hash.outputs.API_HASH }}
      console_hit: ${{ steps.console-already-exists.outputs.cache-hit }}
      core_hit: ${{ steps.core-already-exists.outputs.cache-hit }}
    steps:
    - uses: actions/checkout@v3
    - id: generate-hash
      run: |
        echo "CONSOLE_HASH=console-dist-${{ hashFiles('console/src/**', '!console/src/app/proto/**', 'console/yarn.lock') }}" >> "$GITHUB_OUTPUT"
        echo "CORE_HASH=core-${{hashFiles('build/**', 'cmd/**', 'internal/**', 'pkg/**', 'proto/**', '!*.pb.*', 'go.sum', 'go.mod')}}" >> "$GITHUB_OUTPUT"
    - id: console-already-exists
      name: check console hit
      uses: actions/cache/restore@v3
      with:
        key: ${{ steps.generate-hash.outputs.CONSOLE_HASH }}
        lookup-only: true
        path: .
    - id: core-already-exists
      name: check core hit
      uses: actions/cache/restore@v3
      with:
        key: ${{ steps.generate-hash.outputs.CORE_HASH }}
        lookup-only: true
        path: .