name: Code Coverage
on: push

env:
  REGISTRY: ghcr.io
  NODE_VERSION: '12'
  GO_VERSION: '1.15'

jobs:
  container:
    runs-on: ubuntu-18.04
    steps:
    - name: Source checkout
      uses: actions/checkout@v2
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache-op
        key: ${{ runner.os }}-buildx-op-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-op-
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/dockerfile
        platforms: linux/amd64
        tags: ${{ env.REGISTRY }}/${{ github.repository }}:coverage
        push: false
        cache-from: type=local,src=/tmp/.buildx-cache
        target: go-codecov
        outputs: type=local,dest=/tmp/zitadel
    - uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/operator/Dockerfile
        platforms: linux/amd64
        tags: ${{ env.REGISTRY }}/${{ github.repository }}:coverage
        push: false
        cache-from: type=local,src=/tmp/.buildx-cache-op
        target: go-codecov
        outputs: type=local,dest=/tmp/operator
    - uses: codecov/codecov-action@v1
      with:
        files: /tmp/zitadel/profile.cov,/tmp/operator/profile.cov
        name: codecov-go