name: Compile

on:
  workflow_call:

env:
  core_cache_path: |
    internal/statik/statik.go
    internal/notification/statik/statik.go
    internal/api/ui/login/static/resources/themes/zitadel/css/zitadel.css*
    internal/api/ui/login/statik/statik.go
    internal/api/assets/authz.go 
    internal/api/assets/router.go
    openapi/v2
    pkg/grpc/**/*.pb.*
  console_cache_path: console/dist/console

jobs:
  executable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    
    steps:
    - 
      uses: actions/checkout@v3
    - 
      uses: actions/cache/restore@v3
      name: restore console
      with:
        path: ${{ env.console_cache_path }}
        key: console-${{ hashFiles('console') }}
        fail-on-cache-miss: true
    - 
      uses: actions/cache/restore@v3
      name: restore core
      with:
        path: ${{ env.core_cache_path }}
        key: core-${{ hashFiles( 'go.*', 'openapi', 'cmd', 'pkg/grpc/**/*.go', 'internal') }}
        fail-on-cache-miss: true
    - 
      name: compile
      run: GOOS=${{matrix.goos}} GOARCH=${{matrix.goarch}} make compile_pipeline
    - 
      uses: actions/upload-artifact@v3
      with:
        name: zitadel-${{ matrix.goos }}-${{ matrix.goarch }}
        path: zitadel-${{ matrix.goos }}-${{ matrix.goarch }}
