name: Compile

on:
  workflow_call:
    inputs:
      go_version:
        required: true
        type: string
      core_cache_key:
        required: true
        type: string
      core_cache_path:
        required: true
        type: string
      console_cache_key:
        required: true
        type: string
      console_cache_path:
        required: true
        type: string

jobs:
  executable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    
    steps:
    - 
      uses: actions/checkout@v3
    - 
      uses: actions/cache/restore@v3
      name: restore console
      with:
        path: ${{ inputs.console_cache_path }}
        key: ${{ inputs.console_cache_key }}
        fail-on-cache-miss: true
    - 
      uses: actions/cache/restore@v3
      name: restore core
      with:
        path: ${{ inputs.core_cache_path }}
        key: ${{ inputs.core_cache_key }}
        fail-on-cache-miss: true
    -
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go_version }}
    - 
      name: compile
      run: GOOS=${{matrix.goos}} GOARCH=${{matrix.goarch}} make compile_pipeline
    - run: ls -la internal/api/ui/console/static/
    - 
      uses: actions/upload-artifact@v3
      with:
        name: zitadel-${{ matrix.goos }}-${{ matrix.goarch }}
        path: zitadel-${{ matrix.goos }}-${{ matrix.goarch }}
