name: Console

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string

defaults:
  run:
    working-directory: console

jobs:

  grpc:
    name: generate grpc stub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'
        cache-dependency-path: console/yarn.lock
    - run: yarn install --frozen-lockfile
    - run: yarn generate
    - uses: actions/upload-artifact@v3
      with:
        name: console-grpc-stub
        path: console/src/app/proto/generated
  
  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: [grpc]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'
        cache-dependency-path: console/yarn.lock
    - run: yarn install --frozen-lockfile
    - uses: actions/download-artifact@v3
      with:
        name: console-grpc-stub
        path: console/src/app/proto/generated
    - run: yarn lint

  build:
    name: build and upload
    runs-on: ubuntu-latest
    needs: [grpc]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'
        cache-dependency-path: console/yarn.lock
    - run: yarn install --frozen-lockfile
    - uses: actions/download-artifact@v3
      with:
        name: console-grpc-stub
        path: console/src/app/proto/generated
    - run: yarn build
    ## The upload action is slow with multiple small artifacts
    - run: zip -r bundle.zip dist/console
    - uses: actions/upload-artifact@v3
      with:
        name: console
        path: console/bundle.zip