name: Console

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string

defaults:
  run:
    working-directory: console

jobs:
  
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'
        cache-dependency-path: console/yarn.lock
    - run: yarn install --frozen-lockfile
    - run: yarn generate
    - run: yarn lint

  build:
    name: build and upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'
        cache-dependency-path: console/yarn.lock
    - run: yarn install --frozen-lockfile
    - run: yarn generate
    - run: yarn build
    - run: zip -r bundle.zip dist/console
    - uses: actions/upload-artifact@v3
      with:
        name: console
        path: console/bundle.zip