name: Console

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string

defaults:
  run:
    working-directory: console

jobs:

  deps:
    name: deps
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'
        cache-dependency-path: console/yarn.lock
    - run: yarn install --frozen-lockfile
    - run: yarn generate
    - uses: actions/cache/save@v3
      if: always()
      with:
        path: src/app/proto/generated
        key: console-client-${{ hashFiles('proto/**') }}

  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: deps
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'
        cache-dependency-path: console/yarn.lock
    - uses: actions/cache/restore@v3
      id: cache
      with:
        path: src/app/proto/generated
        key: console-client-${{ hashFiles('proto/**') }}
    - run: yarn lint

  build:
    name: build
    runs-on: ubuntu-latest
    needs: deps
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'
        cache-dependency-path: console/yarn.lock
    - uses: actions/cache/restore@v3
      id: cache
      with:
        path: src/app/proto/generated
        key: console-client-${{ hashFiles('proto/**') }}
    - run: yarn build


