name: Console

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string

defaults:
  run:
    working-directory: console

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'
        cache-dependency-path: console/yarn.lock
    - run: yarn install --frozen-lockfile
    - run: yarn generate
    - run: yarn lint

  build:
    name: build and upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'
        cache-dependency-path: console/yarn.lock
    - run: yarn install --frozen-lockfile
    - run: yarn generate
    - run: yarn build
    ## The upload action is slow with multiple small artifacts
    - run: zip -r bundle.zip dist/console
    - uses: actions/upload-artifact@v3
      with:
        name: console
        path: console/bundle.zip
    
  container:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
      # uses: docker/login-action@v2
      # with:
      #   registry: ghcr.io
      #   username: ${{ github.actor }}
      #   password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/download-artifact@v3
      with:
        name: console
        path: console/bundle.zip
    - run: ls -latr
    - run: unzip bundle.zip
    - uses: docker/build-push-action@v4
      with:
        context: .
        file: build/console/nginx
        push: false
        tags: zitadel/console:${{ github.sha }}  

  success:
    name: check success
    runs-on: ubuntu-latest
    needs: [lint, build,container]
    steps:
    - run: echo "console sucessful built"
