name: Console

on:
  workflow_call:
    inputs:
      node:
        required: true
        type: string

defaults:
  run:
    working-directory: console

jobs:
  
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node }}
        cache: 'pnpm'
        cache-dependency-path: console/pnpm-lock.json
    - run: pnpm install --frozen-lockfile
    - run: pnpm generate
    - run: pnpm lint

  build:
    name: build and upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node }}
        cache: 'pnpm'
        cache-dependency-path: console/pnpm-lock.json
    - run: pnpm install --frozen-lockfile
    - run: pnpm generate
    - run: pnpm build
    - uses: actions/upload-artifact@v3
      with:
        name: console
        path: console/dist/console
