name: Container

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
    outputs:
      tag_name:
        value: ${{ inputs.tag_name }}

jobs:
  build:
    name: zitadel
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64,arm64]
    steps:
      - 
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository }}
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: 'image=moby/buildkit:v0.11.6'
      - 
        name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        uses: actions/download-artifact@v3
        with:
          path: .artifacts
          name: zitadel-linux-${{ matrix.arch }}
      -
        name: Unpack executable
        run: |
          tar -xvf .artifacts/zitadel-linux-${{ matrix.arch }}.tar
          mv zitadel-linux-${{ matrix.arch }}/zitadel ./zitadel
      - 
        name: Ubuntu
        id: build-ubuntu
        uses: docker/build-push-action@v4
        timeout-minutes: 4
        with:
          context: .
          file: build/Dockerfile
          target: artifact
          platforms: linux/${{ matrix.arch }}
          # tags: ${{ inputs.tag_name }}-ubuntu
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ github.repository }},push-by-digest=true,name-canonical=true,push=true
      - 
        name: Scratch
        id: build-scratch
        uses: docker/build-push-action@v4
        timeout-minutes: 4
        with:
          context: .
          file: build/Dockerfile
          target: final
          platforms: linux/${{ matrix.arch }}
          push: true
          # tags: ${{ inputs.tag_name }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ github.repository }},push-by-digest=true,name-canonical=true,push=true
      -
        name: Export ubuntu digest
        run: |
          mkdir -p /tmp/digests/ubuntu
          digest="${{ steps.build-ubuntu.outputs.digest }}"
          touch "/tmp/digests/ubuntu/${digest#sha256:}"
      -
        name: Export scratch digest
        run: |
          mkdir -p /tmp/digests/scratch
          digest="${{ steps.build-scratch.outputs.digest }}"
          touch "/tmp/digests/scratch/${digest#sha256:}"
      -
        name: Upload digest
        uses: actions/upload-artifact@v3
        with:
          name: digests
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1
  
  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      -
        name: Download digests
        uses: actions/download-artifact@v3
        with:
          name: digests
          path: /tmp/digests
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.tag_name }}
      - 
        name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ inputs.tag_name }}@sha256:%s ' *)
      -
        name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ inputs.tag_name }}:${{ steps.meta.outputs.version }}