name: Container

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
      shoud_push:
        required: true
        type: boolean
    outputs:
      tag_name:
        value: ${{ inputs.tag_name }}

env:
  platforms: linux/amd64,linux/arm64
  
jobs:

  core:
    name: core
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
      - 
        name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        uses: actions/download-artifact@v3
      - 
        name: ubuntu
        uses: docker/build-push-action@v4
        with:
          context: .
          file: build/Dockerfile
          target: artifact
          platforms: ${{env.platforms}}
          push: ${{ inputs.shoud_push }}
          load: ${{ inputs.shoud_push != 'true' }}
          tags: ${{ inputs.tag_name }}-ubuntu
          cache-to: type=gha,mode=max
          cache-from: type=gha
      - 
        name: scratch
        uses: docker/build-push-action@v4
        with:
          context: .
          file: build/Dockerfile
          target: final
          platforms: ${{env.platforms}}
          push: ${{ inputs.shoud_push }}
          load: ${{ inputs.shoud_push != 'true' }}
          tags: ${{ inputs.tag_name }}
          cache-to: type=gha,mode=max
          cache-from: type=gha