name: Container

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      go_version:
        required: true
        type: string
      buf_version:
        required: true
        type: string

jobs:

  core:
    name: core
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: build/scratch.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: zitadel/test-zitadel:${{ GITHUB_SHA }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: build/alpine.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: zitadel/test-zitadel:${{ GITHUB_SHA }}-alpine