name: Container

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
  
jobs:

  core:
    name: core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v3
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: build/scratch.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ inputs.tag_name }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: build/alpine.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ inputs.tag_name }}-alpine