name: Build core

on: 
  workflow_call:
    inputs:
      go_version:
        required: true
        type: string
      buf_version:
        required: true
        type: string
      node_version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - 
          uses: actions/checkout@v3
        - 
          uses: actions/cache/restore@v3
          id: cache
          with:
            key: core-${{ hashFiles( 'go.*', 'pkg/grpc', 'openapi', 'internal', 'cmd' ) }}
            restore-keys: |
              core-
            path: |
              'internal/statik/statik.go'
              'internal/notification/statik/statik.go'
              'internal/api/ui/login/static/resources/themes/zitadel/css/zitadel.css*'
              'internal/api/ui/login/statik/statik.go'
              'openapi/v2' 
              'pkg/grpc/**/*.pb.*'
        - 
          if: ${{ steps.cache.outputs.cache-hit != 'true' }}
          uses: bufbuild/buf-setup-action@v1
          with:
            github_token: ${{ github.token }}
            version: ${{ inputs.buf_version }}
        
        - 
          # node to install sass
          if: ${{ steps.cache.outputs.cache-hit != 'true' }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ inputs.node_version }}
        - 
          if: ${{ steps.cache.outputs.cache-hit != 'true' }}
          run: npm install -g sass
        
        - 
          if: ${{ steps.cache.outputs.cache-hit != 'true' }}
          uses: actions/setup-go@v4
          with:
            go-version: ${{ inputs.go_version }}
        - 
          if: ${{ steps.cache.outputs.cache-hit != 'true' }}
          run: make core_build
        - 
          if: ${{ steps.cache.outputs.cache-hit != 'true' }}
          uses: actions/cache/save@v3
          with:
            key: core-${{ hashFiles('go.*', 'pkg/grpc', '!pkg/grpc/**/*.pb.*', 'openapi', '!openapi/v2', 'internal', '!internal/**/statik.go', 'cmd', 'zitadel.css*') }}
            path: |
              'internal/statik/statik.go'
              'internal/notification/statik/statik.go'
              'internal/api/ui/login/static/resources/themes/zitadel/css/zitadel.css*'
              'internal/api/ui/login/statik/statik.go'
              'openapi/v2' 
              'pkg/grpc/**/*.pb.*'
        