name: Core

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      go_version:
        required: true
        type: string
      buf_version:
        required: true
        type: string
 
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ env.go_version }}
        cache: true
    - uses: bufbuild/buf-setup-action@v1
      with:
        version: v1.15.1
        github_token: ${{ github.token }}
    - run: make generate
    - uses: actions/cache/save@v3
      with:
        path: .
        key: core-${{ hashFiles('build/**', 'cmd/**', 'internal/**', 'pkg/**', 'proto/**', '!*.pb.*') }}