name: core

on:
  workflow_call:
    inputs:
      go_version:
        required: true
        type: string

jobs:

  tidy:
    name: tidy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go_version }}
    - run: go mod tidy
  
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: bufbuild/buf-setup-action@v1
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go_version }}
    - run: go version