name: core

on:
  workflow_call:
    inputs:
      go_version:
        required: true
        type: string

jobs:

  tidy:
    name: tidy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go_version }}
    - run: make grpc
    - run: make grpc_copy
    - run: make tidy

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go_version }}
    - run: make grpc
    - run: make grpc_copy
    - run: make test

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go_version }}
    - name: linting
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.50.1
        only-new-issues: true
        skip-pkg-cache: true
    - run: make grpc
    - run: make grpc_copy
    - run: make lint

  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v3
    ## Check if caching is needed
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: ${{ inputs.go_version }}
        project_path: "."
        binary_name: "test-binary"
        extra_files: LICENSE README.md
        md5sum: false
        sha256sum: true
        build_command: make build
        asset_name: zitadel-core--${{ matrix.goos }}/${{ matrix.goarch }}

  container:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        container-os: [scratch, alpine]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        # uses: docker/login-action@v2
        # with:
        #   registry: ghcr.io
        #   username: ${{ github.actor }}
        #   password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: build/${{ matrix.container-os }}
          platforms: linux/amd64,linux/arm64
          push: false
          tags: zitadel/core-${{ matrix.container-os }}:${{ github.sha }}

  success:
    name: check success
    runs-on: ubuntu-latest
    needs: [test, tidy, lint, build, container]
    steps:
    - run: echo "core sucessful built"
