name: Build core

on: 
  workflow_call:
    inputs:
      go_version:
        required: true
        type: string
      core_cache_key:
        required: true
        type: string
      core_cache_path:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: zitadel
          PGUSER: zitadel
          POSTGRES_DB: zitadel
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - 
        uses: actions/checkout@v3
      - 
        uses: actions/cache/restore@v3
        name: restore core
        with:
          path: ${{ inputs.core_cache_path }}
          key: ${{ inputs.core_cache_key }}
          fail-on-cache-miss: true
      -
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go_version }}
      - 
        name: test
        env:
          ZITADEL_MASTERKEY: MasterkeyNeedsToHave32Characters
        run: make core_integration_test
      - 
        name: publish coverage
        uses: codecov/codecov-action@v3.1.4
        with:
          file: profile.cov
          name: core-unit-tests
          flags: core-unit-tests
        