name: core

on:
  workflow_call:
    inputs:
      go_version:
        required: true
        type: string

jobs:

  tidy:
    name: tidy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go_version }}
    - run: make grpc
    - run: make grpc_copy
    - run: make tidy

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go_version }}
    - run: make test

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go_version }}
    - run: make generate
    - name: linting
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.50.1
        only-new-issues: true
        skip-pkg-cache: false
    

  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v3
    ## Check if caching is needed
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: ${{ inputs.go_version }}
        project_path: "."
        extra_files: LICENSE README.md
        md5sum: false
        sha256sum: true
        build_command: make build
        asset_name: zitadel-core-${{ matrix.goos }}/${{ matrix.goarch }}
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
      # uses: docker/login-action@v2
      # with:
      #   registry: ghcr.io
      #   username: ${{ github.actor }}
      #   password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      if: matrix.goos == 'linux'
      with:
        context: .
        file: build/core/scratch
        platforms: ${{ matrix.goos }}/${{ matrix.goarch }}
        push: false
        tags: zitadel/core-scratch:${{ github.sha }}
    - uses: docker/build-push-action@v4
      if: matrix.goos == 'linux'
      with:
        context: .
        file: build/core/alpine
        platforms: ${{ matrix.goos }}/${{ matrix.goarch }}
        push: false
        tags: zitadel/core-alpine:${{ github.sha }}

  success:
    name: success
    runs-on: ubuntu-latest
    needs: [test, tidy, lint, build]
    steps:
    - uses: actions/checkout@v3
    - run: echo "core sucessful built"
