name: "CYPRESS e2e"

on:
#  schedule:
#    - cron: '*/15 * * * *'
  workflow_dispatch:

env:
  ZITADEL_IMAGE: ghcr.io/zitadel/zitadel:v2.0.1

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install NPM Modules
        working-directory: ./console
        run: npm ci --only=dev
      - name: Test
        run: ./e2e/docker-compose.sh run e2e
