name: "CYPRESS e2e"

on:
  push:
    branches:
      - "isolate-cypress"
#  schedule:
#    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: vars
        run: echo "githubref: $GITHUB_REF"
