name: "CYPRESS e2e"

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: doublecheck release reference
        run: echo "githubref: $GITHUB_REF"
