name: devcontainer
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - quickfixci

jobs:
  console-lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/zitadel/devcontainer
          imageName: ghcr.io/zitadel/devcontainer
          push: always
          runCmd: |
            (cd console ; npm run lint)

  go-lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/zitadel/devcontainer
          imageName: ghcr.io/zitadel/devcontainer
          push: always
          runCmd: |
            golangci-lint run --new-from-rev=HEAD~1 --out-format=github-actions

  go-test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/zitadel/devcontainer
          imageName: ghcr.io/zitadel/devcontainer
          push: always
          runCmd: |
            go test ./...

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/zitadel/devcontainer
          imageName: ghcr.io/zitadel/devcontainer
          push: always
          runCmd: |
            (cd console ; npm run build)
            GOOS="linux" GOARCH="amd64" goreleaser build --id prod --snapshot --single-target --rm-dist --output .artifacts/zitadel/zitadel