name: Docs

on:
  pull_request:
    branches: 
    - 'main'
  push:
    branches:
    - 'main'

env:
  PROJECT_ID: zitadel-com
  GAR_LOCATION: europe
  REPOSITORY: docs
  SERVICE: hello
  REGION: europe-west6

permissions:
  contents: 'read'
  pull-requests: 'write'

jobs:
  ## This is only a workaround since nested jobs can't simply pass env vars
  Vars:
    runs-on: ubuntu-latest
    outputs:
      PROJECT_ID: ${{ env.PROJECT_ID }}
      GAR_LOCATION: ${{ env.GAR_LOCATION }}
      REPOSITORY: ${{ env.REPOSITORY }}
      SERVICE: ${{ env.SERVICE }}
      REGION: ${{ env.REGION }}
    steps:
      - run: echo "Exposing env vars"

  Build:
    needs: Vars
    uses: ./.github/workflows/docs-build.yaml
    with:
      PROJECT_ID: ${{ needs.vars.outputs.PROJECT_ID }}
      GAR_LOCATION: ${{ needs.vars.outputs.GAR_LOCATION }}
      REPOSITORY: ${{ needs.vars.outputs.REPOSITORY }}
      SERVICE: ${{ needs.vars.outputs.SERVICE }}
      REGION: ${{ needs.vars.outputs.REGION }}
    secrets:
      SERVICE_ACCOUNT: ${{ secrets.TEST_FFO_DOCS_CLOUDRUN_DEPLOY }}

  Deploy:
    needs: Build
    uses: ./.github/workflows/docs-deploy.yaml
    with:
      PROJECT_ID: ${{ needs.vars.outputs.PROJECT_ID }}
      GAR_LOCATION: ${{ needs.vars.outputs.GAR_LOCATION }}
      REPOSITORY: ${{ needs.vars.outputs.REPOSITORY }}
      SERVICE: ${{ needs.vars.outputs.SERVICE }}
      REGION: ${{ needs.vars.outputs.REGION }}
      PRODUCTION: ${{ github.ref == 'refs/heads/main'}}
    secrets:
      SERVICE_ACCOUNT: ${{ secrets.TEST_FFO_DOCS_CLOUDRUN_DEPLOY }}