name: Docs

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string

defaults:
  run:
    working-directory: docs

jobs:

  build:
    name: build and upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'
        cache-dependency-path: docs/yarn.lock
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: zip -r bundle.zip build
    - uses: actions/upload-artifact@v3
      with:
        name: docs
        path: docs/bundle.zip
