name: "ZITADEL e2e Tests"

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string

jobs:
  test:
    strategy:
      matrix:
        browser: [firefox, chrome]
    services:
      # we currently use postgres because cockroach doesn't work
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: zitadel
          PGUSER: zitadel
          POSTGRES_DB: zitadel
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      zitadel:
        image: ${{ inputs.tag_name }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        options: >-
          --health-cmd "sh curl http://localhost:8080/management/v1/healthz || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 8080:8080
        volumes:
          - e2e/config/github/zitadel.yaml:/app/zitadel.yaml
        env:
          ZITADEL_ARGS: "start-from-init --masterkeyFromEnv --config /app/zitadel.yaml --steps /app/zitadel.yaml"
          ZITADEL_MASTERKEY: MasterkeyNeedsToHave32Characters
          ZITADEL_LOG_LEVEL: debug
          ZITADEL_EXTERNALDOMAIN: localhost
          ZITADEL_EXTERNALSECURE: false
          ZITADEL_TLS_ENABLED: false
          ZITADEL_DATABASE_postgres_HOST: postgres
          ZITADEL_DATABASE_postgres_PORT: 5432
          ZITADEL_DATABASE_postgres_DATABASE: zitadel
          ZITADEL_DATABASE_postgres_MAXOPENCONNS: 20
          ZITADEL_DATABASE_postgres_MAXIDLECONNS: 10
          ZITADEL_DATABASE_postgres_USER_USERNAME: zitadel
          ZITADEL_DATABASE_postgres_USER_SSL_MODE: disable
          ZITADEL_DATABASE_postgres_ADMIN_USERNAME: zitadel
          ZITADEL_DATABASE_postgres_ADMIN_SSL_MODE: disable
          ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: false
          ZITADEL_LOGSTORE_ACCESS_DATABASE_ENABLED: true
          ZITADEL_LOGSTORE_ACCESS_DATABASE_DEBOUNCE_MINFREQUENCY: 0s
          ZITADEL_LOGSTORE_ACCESS_DATABASE_DEBOUNCE_MAXBULKSIZE: 0
          ZITADEL_LOGSTORE_EXECUTION_DATABASE_ENABLED: true
          ZITADEL_LOGSTORE_EXECUTION_STDOUT_ENABLED: false
          ZITADEL_QUOTAS_ACCESS_EXHAUSTEDCOOKIEKEY: "zitadel.quota.limiting"
          ZITADEL_QUOTAS_ACCESS_EXHAUSTEDCOOKIEMAXAGE: "60s"
          ZITADEL_PROJECTIONS_CUSTOMIZATIONS_NOTIFICATIONSQUOTAS_REQUEUEEVERY: 1s
          ZITADEL_DEFAULTINSTANCE_LOGINPOLICY_MFAINITSKIPLIFETIME: "0"
          ZITADEL_SYSTEMAPIUSERS_CYPRESS_KEYDATA: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6aStGRlNKTDdmNXl3NEtUd3pnTQpQMzRlUEd5Y20vTStrVDBNN1Y0Q2d4NVYzRWFESXZUUUtUTGZCYUVCNDV6YjlMdGpJWHpEdzByWFJvUzJoTzZ0CmgrQ1lRQ3ozS0N2aDA5QzBJenhaaUIySVMzSC9hVCs1Qng5RUZZK3ZuQWtaamNjYnlHNVlOUnZtdE9sbnZJZUkKSDdxWjB0RXdrUGZGNUdFWk5QSlB0bXkzVUdWN2lvZmRWUVMxeFJqNzMrYU13NXJ2SDREOElkeWlBQzNWZWtJYgpwdDBWajBTVVgzRHdLdG9nMzM3QnpUaVBrM2FYUkYwc2JGaFFvcWRKUkk4TnFnWmpDd2pxOXlmSTV0eXhZc3duCitKR3pIR2RIdlczaWRPRGxtd0V0NUsycGFzaVJJV0syT0dmcSt3MEVjbHRRSGFidXFFUGdabG1oQ2tSZE5maXgKQndJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="

    runs-on: ubuntu-latest
    env:
      ZITADEL_IMAGE: ${{ inputs.tag_name }}
    steps:
      - 
        name: Checkout Repository
        uses: actions/checkout@v3
      - 
        name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: e2e
          build: npm run build
          start: npm start
          browser: ${{ matrix.browser }}
      - 
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: production-tests-${{ matrix.browser }}
          path: |
            e2e/cypress/screenshots
            e2e/cypress/videos
            e2e/cypress/results
          retention-days: 30

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      #   with:
      #     driver: docker
      #     install: true
      # - name: Test ${{ matrix.browser }}
      #   run: docker compose run --service-ports e2e --browser ${{ matrix.browser }}
      #   working-directory: e2e/config/host.docker.internal
      # - name: Ensure Artifacts Directory Exists
      #   run: mkdir -p ./.artifacts
      # - name: Save ZITADEL Logs
      #   if: always()
      #   run: docker compose logs zitadel > ../../../.artifacts/e2e-compose-zitadel.log
      #   working-directory: e2e/config/host.docker.internal
      # - name: Save Prepare Logs
      #   if: always()
      #   run: docker compose logs prepare > ../../../.artifacts/e2e-compose-prepare.log
      #   working-directory: e2e/config/host.docker.internal
      # - name: Archive production tests ${{ matrix.browser }}
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: production-tests-${{ matrix.browser }}
      #     path: |
      #       e2e/cypress/results
      #       e2e/cypress/videos
      #       e2e/cypress/screenshots
      #       .artifacts/e2e-compose-zitadel.log
      #       .artifacts/e2e-compose-prepare.log
      #     retention-days: 30
