name: Lint

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      go_version:
        required: true
        type: string
      core_cache_key:
        required: true
        type: string
      core_cache_hit:
        required: true
        type: string
      core_cache_path:
        required: true
        type: string
      console_cache_key:
        required: true
        type: string
      console_cache_path:
        required: true
        type: string
      console_cache_hit:
        required: true
        type: string

jobs:

  api:
    name: api
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - 
      uses: actions/checkout@v2
    - 
      uses: bufbuild/buf-setup-action@v1
    - 
      name: lint
      uses: bufbuild/buf-lint-action@v1

  console:
    # if: ${{ inputs.console_cache_hit != 'true' }}
    name: console
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    - 
      uses: actions/cache/restore@v3
      name: restore console
      with:
        path: ${{ inputs.console_cache_path }}
        key: ${{ inputs.console_cache_key }}
        fail-on-cache-miss: true
    -
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'
        cache-dependency-path: console/yarn.lock
    -
      name: lint
      run: make console_lint

  core:
    # if: ${{ inputs.core_cache_hit != 'true' }}
    name: core
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    - 
      uses: actions/cache/restore@v3
      name: restore core
      with:
        path: ${{ inputs.core_cache_path }}
        key: ${{ inputs.core_cache_key }}
        fail-on-cache-miss: true
    - 
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go_version }}
        cache: false
    - 
      uses: golangci/golangci-lint-action@v3
    # -
    #   name: lint
    #   run: make core_lint
