name: Lint

on:
  workflow_call:
    inputs:
      buildx_driver_opts:
        required: true
        type: string
      cache_from_params:
        required: true
        type: string
      cache_to_params:
        required: true
        type: string
      tag_name:
        required: true
        type: string

jobs:

  api:
    name: api
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: ${{inputs.buildx_driver_opts}}
      - 
        name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Lint
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./build/workflow.Dockerfile
          target: lint-api
          push: false
          cache-to: ${{inputs.cache_to_params}}
          cache-from: ${{inputs.cache_from_params}}
          github-token: ${{ github.token }}
          tags: ${{inputs.tag_name}}

  console:
    name: console
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: ${{inputs.buildx_driver_opts}}
    - 
      name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Lint
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./build/workflow.Dockerfile
        target: lint-console
        push: false
        cache-to: ${{inputs.cache_to_params}}
        cache-from: ${{inputs.cache_from_params}}
        github-token: ${{ github.token }}
        tags: ${{inputs.tag_name}}

  core:
    name: core
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: ${{inputs.buildx_driver_opts}}
    - 
      name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Lint
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./build/workflow.Dockerfile
        target: lint-core
        push: false
        cache-to: ${{inputs.cache_to_params}}
        cache-from: ${{inputs.cache_from_params}}
        github-token: ${{ github.token }}
        tags: ${{inputs.tag_name}}
