name: Release

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      buf_version:
        required: true
        type: string
      semantic_version:
        required: true
        type: string
      tag_name:
        required: true
        type: string
      image_name:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      release: ${{ steps.semantic.outputs.new_release_version }}
      published: ${{ steps.semantic.outputs.new_release_published }}
    steps:
    - name: Source checkout
      uses: actions/checkout@v3
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        dry_run: true
        semantic_version: ${{ inputs.semantic_version }}
        extra_plugins: |
          @semantic-release/exec@6.0.3
    
  docker:
    runs-on: ubuntu-22.04
    needs: [release]
    if: ${{ needs.release.outputs.published == 'true' }}
    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - 
      name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Publish v${{ needs.release.outputs.release }}
      run: |
        docker buildx imagetools create \
          --tag ${{ inputs.image_name }}:v${{ needs.release.outputs.release }} \
          ${{ inputs.tag_name }}
    -
      name: Publish latest
      if: ${{ github.ref_name == 'main' }}
      run: |
        docker buildx imagetools create \
          --tag ${{ inputs.image_name }}:latest \
          ${{ inputs.tag_name }}





    
  # api:
  #   name: api
  #   runs-on: ubuntu-latest
  #   needs: [release]
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: bufbuild/buf-setup-action@v1
  #     with:
  #       version: ${{ inputs.buf_version }}
  #       github_token: ${{ github.token }}
  #   - uses: bufbuild/buf-push-action@v1
  #     with:
  #       buf_token: ${{ secrets.buf_token }}
  #       # input: proto
  #       ## Currently no tags are supported in the action https://github.com/bufbuild/buf-push-action/issues/20
  #       draft: ${{ github.ref_name != 'main'}}

  #console:

  #core:
