name: Release

on:
  push:
    branches:
      - ci/improve-no-pr
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      buf_version:
        required: true
        type: string
      semantic_version:
        required: true
        type: string
      tag_name:
        required: true
        type: string
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Source checkout
      uses: actions/checkout@v3
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        dry_run: true
        semantic_version: ${{ inputs.semantic_version }}
        extra_plugins: |
          @semantic-release/exec@6.0.3
    - run: |
        echo "${{ steps.semantic.outputs.new_release_published }}"
        echo "${{ steps.semantic.outputs.new_release_version }}"
        echo "${{ steps.semantic.outputs.new_release_major_version }}"
        echo "${{ steps.semantic.outputs.new_release_minor_version }}"
        echo "${{ steps.semantic.outputs.new_release_patch_version }}"
        echo "${{ steps.semantic.outputs.new_release_channel }}"
        echo "${{ steps.semantic.outputs.new_release_notes }}"
        echo "${{ steps.semantic.outputs.new_release_git_head }}"
        echo "${{ steps.semantic.outputs.new_release_git_tag }}"
        echo "${{ steps.semantic.outputs.last_release_version }}"
        echo "${{ steps.semantic.outputs.last_release_git_head }}"
        echo "${{ steps.semantic.outputs.last_release_git_tag }}"
    
  # api:
  #   name: api
  #   runs-on: ubuntu-latest
  #   needs: [release]
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: bufbuild/buf-setup-action@v1
  #     with:
  #       version: ${{ inputs.buf_version }}
  #       github_token: ${{ github.token }}
  #   - uses: bufbuild/buf-push-action@v1
  #     with:
  #       buf_token: ${{ secrets.buf_token }}
  #       # input: proto
  #       ## Currently no tags are supported in the action https://github.com/bufbuild/buf-push-action/issues/20
  #       draft: ${{ github.ref_name != 'main'}}

  #console:

  #core:
