name: Release

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      go_version:
        required: true
        type: string
      buf_version:
        required: true
        type: string

jobs:

  api:
    name: api
    runs-on: ubuntu-latest
    # needs: [lint, breaking]
    steps:
    - uses: actions/checkout@v3
    - uses: bufbuild/buf-setup-action@v1
      with:
        version: ${{ inputs.buf_version }}
        github_token: ${{ github.token }}
    - uses: bufbuild/buf-push-action@v1
      with:
        buf_token: ${{ secrets.buf_token }}
        input: proto
        ## Currently no tags are supported in the action https://github.com/bufbuild/buf-push-action/issues/20
        draft: ${{ github.ref_name != 'main'}}

  #console:

  #core:
