name: Release
on: push

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REGISTRY: docker.pkg.github.com
  IMAGE: zitadel
  NODE_VERSION: '12'
  GO_VERSION: '^1.13.1'

jobs:

  prepare:
    runs-on: ubuntu-18.04
    steps: 
    - name: Generate Short SHA Container Tag
      id: vars
      run: echo "::set-output name=sha_short::SHA-$(git rev-parse --short HEAD)"
    - name: Check outputs
      run: echo ${{ steps.vars.outputs.sha_short }}

  angular:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: echo "hodor" > hodor.txt
    # - run: npm ci 
    # - run: npm run lint
    # - run: npm run prodbuild
    # - run: npm test
    - uses: actions/upload-artifact@v1
      with:
        name: angular
        path: hodor.txt
  
  go:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.13.1'
    - run: go test -race ./...
    - run: go build -o zitadel main.go
    - uses: actions/upload-artifact@v1
      with:
        name: go
        path: zitadel

  container:
    runs-on: ubuntu-18.04
    needs: [angular, go]
    steps:
    - name: Source checkout
      uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: angular
        path: angular
    - uses: actions/download-artifact@v1
      with:
        name: go
        path: go
    - run: ls -la
    - uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: ${{ env.REGISTRY }}
        repository: ${{ github.repository }}/${{ env.IMAGE }}
        tag_with_ref: true
        tag_with_sha: true

  container-vulnerability-scan:
    runs-on: ubuntu-18.04
    needs: [container]
    steps:
    - name: Source checkout
      uses: actions/checkout@v2
    - name: Docker Login
      run: docker login $REGISTRY -u $GITHUB_ACTOR -p $GITHUB_TOKEN
    - uses: anchore/scan-action@master
      with:
        image-reference: "${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE }}:$${{ steps.vars.outputs.sha_short }}"
        dockerfile-path: "./Dockerfile"
        fail-build: false
    - name: anchore inline scan JSON results
      run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done

  container-test:
    runs-on: ubuntu-18.04
    needs: [container]
    steps:
    - name: Source checkout
      uses: actions/checkout@v2
    - name: Docker Login
      run: docker login $REGISTRY -u $GITHUB_ACTOR -p $GITHUB_TOKEN
    - name: Docker Run Test
      run: docker run $REGISTRY/${GITHUB_REPOSITORY}/$IMAGE:$${{ steps.vars.outputs.sha_short }} /bin/bash -c "./app/zitadel | cat /app/console/hodor.txt"

  release:
    runs-on: ubuntu-18.04
    needs: [container-test]
    steps:
    - name: Source checkout
      uses: actions/checkout@v2
    - name: Create Version
      uses: caos/semantic-release@v0.2.4
