name: ZITADEL PR

on:
  pull_request:
#    paths:
#      - "docs/**"
#      - "**.md"

jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
      - name: Source checkout
        uses: actions/checkout@v2
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --check **/*.md,docs/docs
