name: Go Unit Test
on:
  push:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: ['1.14', '1.15', '1.16', '1.17']
    name: Go ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test -race -v -coverprofile=profile.cov ./pkg/...
      - uses: codecov/codecov-action@v2.1.0
        with:
          file: ./profile.cov
          name: codecov-go