name: ZITADEL PR

on:
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-20.04
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Source checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
          install: true
      - name: Set up Docker Image Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          install-only: true
          version: v1.8.3
      - name: Install NPM Modules
        working-directory: ./console
        run: npm ci
      - name: Test
        run: ./e2e/install.sh
      - name: Publish go coverage
        uses: codecov/codecov-action@v3.1.0
        with:
          file: .artifacts/codecov/profile.cov
          name: go-codecov

