name: ZITADEL PR

on:
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-20.04
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Source checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
          install: true
      - name: Run Environment
        run: ./e2e/install.sh
      - name: Prepare for E2E Tests
        run: ./e2e/e2e-setup.sh
      - name: Run E2E Tests
        run: cd ./console && npm run e2e
      - name: Publish go coverage
        uses: codecov/codecov-action@v3.1.0
        with:
          file: .artifacts/codecov/profile.cov
          name: go-codecov

