name: ZITADEL Release

on:
  #pull_request:
  push:

permissions:
  contents: write

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: Source checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          dry_run: true
          semantic_version: 19.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/grpc/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          tags: zitadel-base:latest
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        continue-on-error: true
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: docker buildx build -f build/grpc/Dockerfile -t zitadel-local/base:latest .
      - run: docker images
